name: FastAPI CI/CD Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Decode the Base64-encoded PEM file and set up SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.PEM_FILE_BASE64 }} | fromJson | base64Decode

      # Step 5: Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/your/project
            git pull origin dev
            source /path/to/venv/bin/activate
            pip install -r requirements.txt
            # Optional: Apply database migrations if applicable
            # Example: alembic upgrade head
            sudo systemctl restart your-fastapi-service
          EOF

      # Step 6: Notify on successful deployment (Optional)
      - name: Notify deployment
        run: echo "Deployment to EC2 successful!"
