name: FastAPI CI/CD Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Decode the Base64-encoded PEM file and set up SSH
      - name: Decode PEM file and setup SSH
        run: |
          echo "${{ secrets.PEM_FILE_BASE64 }}" | base64 --decode > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Setup SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_FILE_BASE64 }}

      # Step 5: Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /AudioTextify
            git pull origin dev
            source /venve/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart your-fastapi-service
          EOF

      # Step 6: Notify on successful deployment (Optional)
      - name: Notify deployment
        run: echo "Deployment to EC2 successful!"
